### ISSUE TITLE
Credential requirements

### ISSUE THREAD

**Issue by grahamhar** [sonatype-nexus-community/terraform-provider-sonatypeiq#14]
Hi,

In the documentation from the provider it suggest the administrator user and password are required. I am hoping to use this provider to allow a subset of users to manage their applications under an organisation. I would like to confirm that this will work by providing their API credentials scoped with permissions for the resource they will be creating?

**Comment by madpah** [comment]
Hi @grahamhar - thanks for the question.

This is something that we have not tested internally at this time with this provider, but we expect that the permissions granted to the user for which you supply credentials to this provider should be respected. There is nothing in this provider itself that performs any restriction - any restriction would be purely in the Sonatype IQ Server's REST API's themselves.

If this does not work as you suggest, then we can recommend a route via Customer Support (assumption that you are a current Sonatype Customer).

A quick test here does confirm this should work as you describe. Do let us know if you hit any issues.

Thanks

**Comment by grahamhar** [comment]
I'll do a pr to update the docs as this might lead people to think the module won't work for them.

**Comment by madpah** [comment]
That is greatly appreciated @grahamhar!
