### ISSUE TITLE
Organization - BLOCKED (missing DELETE API)

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/terraform-provider-sonatypeiq#2]

**Comment by iverberk** [comment]
It does not seem to be documented but inspecting the UI shows a DELETE request to /rest/organization/$org_id. Maybe this is usable?

**Comment by madpah** [comment]
@iverberk - calls to /rest/* endpoints are internal only and cannot be relied upon unfortunately (they are also not RESTful).

However, IQ 171 has introduced a new public REST API for this operation: `DELETE /api/v2/organizations/{organizationId}` - so we can proceed.
