### ISSUE TITLE
unable to add resource Organization or sub-organization

### ISSUE THREAD

**Issue by Haak1981** [sonatype-nexus-community/terraform-provider-sonatypeiq#4]
Hello,
Using the provider I am getting the following error when trying to setup an Organization or sub-organization:

```
Error: Value Conversion Error
│
│   with sonatypeiq_organization.tenant,
│ An unexpected error was encountered trying to convert tftypes.Value into provider.organizationModelResouce. This is always an error in the provider. Please report the following to the provider developer:
│
│ mismatch between struct and object: Object defines fields not found in struct: tags, id, name, and parent_organization_id.
╵
╷
│ Error: Value Conversion Error
│
│   with sonatypeiq_organization.sub_org,
│ An unexpected error was encountered trying to convert tftypes.Value into provider.organizationModelResouce. This is always an error in the provider. Please report the following to the provider developer:
│
│ mismatch between struct and object: Object defines fields not found in struct: name, parent_organization_id, tags, and id.
```

It seems to be an issue in the provider code.

I've also tested the resource to add a proxy and to set the Base-url ands these work well. 

This is the tf-file I'm using for the Organization:

```
data "sonatypeiq_organization" "sandbox" {
  name = "Sandbox Organization"
}

resource "sonatypeiq_organization" "sub_org" {
  name                   = "Sub Organization"
  parent_organization_id = data.sonatypeiq_organization.sandbox.id
}

output "sub_org_id" {
  value = sonatypeiq_organization.sub_org.id
}
```

thanks!

**Comment by madpah** [comment]
Thanks for the report @Haak1981.

To allow us to look further into this, please can you confirm:

1. What version of Sonatype IQ Server you are running?

Thanks!

**Comment by Haak1981** [comment]
Hi @madpah , we are currently running 170.

**Comment by madpah** [comment]
@Haak1981 - we've released 0.2.0 https://registry.terraform.io/providers/sonatype-nexus-community/sonatypeiq/latest - are you able to retest this?

Thanks!

**Comment by Haak1981** [comment]
ok nice, I'll get right on it!

**Comment by Haak1981** [comment]
Yes, looks good! Just tested adding an organization and it worked. Thanks a bunch! I'll do some more testing the coming weeks
