### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by iverberk** [sonatype-nexus-community/terraform-provider-sonatypeiq#6]
Hi @madpah,

I'm currently investigating if I can extend the provider with some resources that I need (e.g. roles, user access, etc.). What are your plans for the provider? Is this still being developed?

Thanks!

**Comment by madpah** [comment]
Hey @iverberk - great to hear from you.

There are plans, but as this is a Community offering from Sonatype, there is no commitment at this time to deliver to a specific timeline.

It would be great to get a list of specific things you'd like to see, and I can prioritise work on these when time permits.

**Comment by madpah** [comment]
FYI - please add to https://github.com/sonatype-nexus-community/terraform-provider-sonatypeiq/issues/1 - as this was my list of initial items to tackle.
